SAMPLES: [BP6,BM10,BM13,BM20,OM17,OP11,OP9,OP15,OP14,BM18,BM29,OM14,OM6,OM12,OP13,BM21,BM9,BM17,BP2,OM26,OP10,OP18,OP19,BM16,Ctrl,LP,BM20_alisa,OP34,control_8-12]

PROJECT: 
    'BP6': CHIPS

    'BM10': CHIPS

    'BM13': CHIPS

    'BM20': CHIPS

    'OM17': CHIPS

    'OP11': CHIPS

    'OP9': CHIPS

    'OP15': CHIPS

    'OP14': CHIPS

    'BM18': CHIPS

    'BM29': CHIPS

    'OM14': CHIPS

    'OM6': CHIPS

    'OM12': CHIPS

    'OP13': CHIPS

    'BM21': CHIPS

    'BM9': CHIPS

    'BM17': CHIPS

    'BP2': CHIPS

    'OM26': CHIPS

    'OP10': CHIPS

    'OP18': CHIPS

    'OP19': CHIPS

    'BM16': CHIPS

    'Ctrl': CHIPS

    'LP': CHIPS

    'BM20_alisa': CHIPS

    'OP34': CHIPS

    'control_8-12': CHIPS

PREP: 
    'BP6': SMARTer_pico_v2

    'BM10': SMARTer_pico_v2

    'BM13': SMARTer_pico_v2

    'BM20': SMARTer_pico_v2

    'OM17': SMARTer_pico_v2

    'OP11': SMARTer_pico_v2

    'OP9': SMARTer_pico_v2

    'OP15': SMARTer_pico_v2

    'OP14': SMARTer_pico_v2

    'BM18': SMARTer_pico_v2

    'BM29': SMARTer_pico_v2

    'OM14': SMARTer_pico_v2

    'OM6': SMARTer_pico_v2

    'OM12': SMARTer_pico_v2

    'OP13': SMARTer_pico_v2

    'BM21': SMARTer_pico_v2

    'BM9': SMARTer_pico_v2

    'BM17': SMARTer_pico_v2

    'BP2': SMARTer_pico_v2

    'OM26': SMARTer_pico_v2

    'OP10': SMARTer_pico_v2

    'OP18': SMARTer_pico_v2

    'OP19': SMARTer_pico_v2

    'BM16': SMARTer_pico_v2

    'Ctrl': SMARTer_pico_v2

    'LP': SMARTer_pico_v2

    'BM20_alisa': SMARTer_pico_v2

    'OP34': SMARTer_pico_v2

    'control_8-12': SMARTer_pico_v2

REF_DICT: 
    'BP6': HG38

    'BM10': HG38

    'BM13': HG38

    'BM20': HG38

    'OM17': HG38

    'OP11': HG38

    'OP9': HG38

    'OP15': HG38

    'OP14': HG38

    'BM18': HG38

    'BM29': HG38

    'OM14': HG38

    'OM6': HG38

    'OM12': HG38

    'OP13': HG38

    'BM21': HG38

    'BM9': HG38

    'BM17': HG38

    'BP2': HG38

    'OM26': HG38

    'OP10': HG38

    'OP18': HG38

    'OP19': HG38

    'BM16': HG38

    'Ctrl': HG38

    'LP': HG38

    'BM20_alisa': HG38

    'OP34': HG38

    'control_8-12': HG38

