SAMPLES: [NCOV3289CHOA_MINISEQ_210619,NCOV3343CHOA_MINISEQ_210619,NCOV3318CHOA_MINISEQ_210619,NCOV3342CHOA_MINISEQ_210619,NCOV3333CHOA_MINISEQ_210619,NCOV3329CHOA_MINISEQ_210619,NCOV3287CHOA_MINISEQ_210619,NCOV3312CHOA_MINISEQ_210619,NCOV3265CHOA_MINISEQ_210619]

PROJECT: 
    'NCOV3289CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3343CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3318CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3342CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3333CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3329CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3287CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3312CHOA_MINISEQ_210619': MISC_DNA_test

    'NCOV3265CHOA_MINISEQ_210619': MISC_DNA_test

PREP: 
    'NCOV3289CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3343CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3318CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3342CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3333CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3329CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3287CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3312CHOA_MINISEQ_210619': SMARTer_pico_v2

    'NCOV3265CHOA_MINISEQ_210619': SMARTer_pico_v2

REF_DICT: 
    'NCOV3289CHOA_MINISEQ_210619': HG38

    'NCOV3343CHOA_MINISEQ_210619': HG38

    'NCOV3318CHOA_MINISEQ_210619': HG38

    'NCOV3342CHOA_MINISEQ_210619': HG38

    'NCOV3333CHOA_MINISEQ_210619': HG38

    'NCOV3329CHOA_MINISEQ_210619': HG38

    'NCOV3287CHOA_MINISEQ_210619': HG38

    'NCOV3312CHOA_MINISEQ_210619': HG38

    'NCOV3265CHOA_MINISEQ_210619': HG38

