SAMPLES: [BP6,BM10,BM13,BM20,OM17,OP11,OP9,OP15,OP14,BM18,OM14,OM6,OM12,OP13,BM21,BM9,BM17,BP2,OM26,OP10,OP18,OP19,BM16,short_10000]

PROJECT: 
    BP6: CHIPS

    BM10: CHIPS

    BM13: CHIPS

    BM20: CHIPS

    OM17: CHIPS

    OP11: CHIPS

    OP9: CHIPS

    OP15: CHIPS

    OP14: CHIPS

    BM18: CHIPS

    OM14: CHIPS

    OM6: CHIPS

    OM12: CHIPS

    OP13: CHIPS

    BM21: CHIPS

    BM9: CHIPS

    BM17: CHIPS

    BP2: CHIPS

    OM26: CHIPS

    OP10: CHIPS

    OP18: CHIPS

    OP19: CHIPS

    BM16: CHIPS

    short_10000: TEST

PREP: 
    BP6: SMARTer_pico_v2

    BM10: SMARTer_pico_v2

    BM13: SMARTer_pico_v2

    BM20: SMARTer_pico_v2

    OM17: SMARTer_pico_v2

    OP11: SMARTer_pico_v2

    OP9: SMARTer_pico_v2

    OP15: SMARTer_pico_v2

    OP14: SMARTer_pico_v2

    BM18: SMARTer_pico_v2

    OM14: SMARTer_pico_v2

    OM6: SMARTer_pico_v2

    OM12: SMARTer_pico_v2

    OP13: SMARTer_pico_v2

    BM21: SMARTer_pico_v2

    BM9: SMARTer_pico_v2

    BM17: SMARTer_pico_v2

    BP2: SMARTer_pico_v2

    OM26: SMARTer_pico_v2

    OP10: SMARTer_pico_v2

    OP18: SMARTer_pico_v2

    OP19: SMARTer_pico_v2

    BM16: SMARTer_pico_v2

    short_10000: SMARTer_pico_v2

