SAMPLES: [mock1_6-24,mock2_6-24,t1l1_6-24,t1l2_6-24,k287t1_6-24,k287t2_6-24,control_6-26]

PROJECT: 
    mock1_6-24: MOUSE_INF

    mock2_6-24: MOUSE_INF

    t1l1_6-24: MOUSE_INF

    t1l2_6-24: MOUSE_INF

    k287t1_6-24: MOUSE_INF

    k287t2_6-24: MOUSE_INF

    control_6-26: MOUSE_INF

PREP: 
    mock1_6-24: SMARTer_pico_v2

    mock2_6-24: SMARTer_pico_v2

    t1l1_6-24: SMARTer_pico_v2

    t1l2_6-24: SMARTer_pico_v2

    k287t1_6-24: SMARTer_pico_v2

    k287t2_6-24: SMARTer_pico_v2

    control_6-26: SMARTer_pico_v2

REF_DICT: 
    mock1_6-24: GRCm38

    mock2_6-24: GRCm38

    t1l1_6-24: GRCm38

    t1l2_6-24: GRCm38

    k287t1_6-24: GRCm38

    k287t2_6-24: GRCm38

    control_6-26: GRCm38

