SAMPLES: [UCSF_S2047,UCSF_S2048,UCSF_S2049,UCSF_S2097,UCSF_S2098,UCSF_S2151,UCSF_S2152,UCSF_control.b1]

PROJECT: 
    UCSF_S2047: MISC

    UCSF_S2048: MISC

    UCSF_S2049: MISC

    UCSF_S2097: MISC

    UCSF_S2098: MISC

    UCSF_S2151: MISC

    UCSF_S2152: MISC

    UCSF_control.b1: MISC

PREP: 
    UCSF_S2047: SMARTer_pico_v2

    UCSF_S2048: SMARTer_pico_v2

    UCSF_S2049: SMARTer_pico_v2

    UCSF_S2097: SMARTer_pico_v2

    UCSF_S2098: SMARTer_pico_v2

    UCSF_S2151: SMARTer_pico_v2

    UCSF_S2152: SMARTer_pico_v2

    UCSF_control.b1: SMARTer_pico_v2

