SAMPLES: [short_10000,PTCOV128]

PROJECT: 
    'short_10000': TEST

    'PTCOV128': MISC

PREP: 
    'short_10000': SMARTer_pico_v2

    'PTCOV128': SMARTer_pico_v2

REF_DICT: 
    'short_10000': HG38

    'PTCOV128': HG38

