SAMPLES: ['T16','T16.10000']

PROJECT: 
    'T16': MOUSE_INF

    'T16.10000': MOUSE_INF

PREP: 
    'T16': SMARTer_pico_v3

    'T16.10000': SMARTer_pico_v3

REF_DICT: 
    'T16': GRCm38

    'T16.10000': GRCm38

