SAMPLES: [BP6,BM10,BM13,BM20,OM17,OP11,OP9,OP15,OP14,BM18,BM29,OM14,OM6,OM12,OP13,BM21,BM9,BM17,BP2,OM26,OP10,OP18,OP19,BM16,Ctrl,LP,BM20_alisa,SRR13795948,SRR13795968,SRR13795969,SRR13796010,SRR13796112,SRR13796113,SRR13796114,SRR13796120,SRR13796121,SRR13795952,SRR13795964,SRR13795965,SRR13796011,SRR13796110,SRR13796111,SRR13796115,SRR13796118,SRR13796119]

PROJECT: 
    BP6: CHIPS

    BM10: CHIPS

    BM13: CHIPS

    BM20: CHIPS

    OM17: CHIPS

    OP11: CHIPS

    OP9: CHIPS

    OP15: CHIPS

    OP14: CHIPS

    BM18: CHIPS

    BM29: CHIPS

    OM14: CHIPS

    OM6: CHIPS

    OM12: CHIPS

    OP13: CHIPS

    BM21: CHIPS

    BM9: CHIPS

    BM17: CHIPS

    BP2: CHIPS

    OM26: CHIPS

    OP10: CHIPS

    OP18: CHIPS

    OP19: CHIPS

    BM16: CHIPS

    Ctrl: CHIPS

    LP: CHIPS

    BM20_alisa: CHIPS

    SRR13795948: PHYS_2020_CHALASANI

    SRR13795968: PHYS_2020_CHALASANI

    SRR13795969: PHYS_2020_CHALASANI

    SRR13796010: PHYS_2020_CHALASANI

    SRR13796112: PHYS_2020_CHALASANI

    SRR13796113: PHYS_2020_CHALASANI

    SRR13796114: PHYS_2020_CHALASANI

    SRR13796120: PHYS_2020_CHALASANI

    SRR13796121: PHYS_2020_CHALASANI

    SRR13795952: PHYS_2020_CHALASANI

    SRR13795964: PHYS_2020_CHALASANI

    SRR13795965: PHYS_2020_CHALASANI

    SRR13796011: PHYS_2020_CHALASANI

    SRR13796110: PHYS_2020_CHALASANI

    SRR13796111: PHYS_2020_CHALASANI

    SRR13796115: PHYS_2020_CHALASANI

    SRR13796118: PHYS_2020_CHALASANI

    SRR13796119: PHYS_2020_CHALASANI

PREP: 
    BP6: SMARTer_pico_v2

    BM10: SMARTer_pico_v2

    BM13: SMARTer_pico_v2

    BM20: SMARTer_pico_v2

    OM17: SMARTer_pico_v2

    OP11: SMARTer_pico_v2

    OP9: SMARTer_pico_v2

    OP15: SMARTer_pico_v2

    OP14: SMARTer_pico_v2

    BM18: SMARTer_pico_v2

    BM29: SMARTer_pico_v2

    OM14: SMARTer_pico_v2

    OM6: SMARTer_pico_v2

    OM12: SMARTer_pico_v2

    OP13: SMARTer_pico_v2

    BM21: SMARTer_pico_v2

    BM9: SMARTer_pico_v2

    BM17: SMARTer_pico_v2

    BP2: SMARTer_pico_v2

    OM26: SMARTer_pico_v2

    OP10: SMARTer_pico_v2

    OP18: SMARTer_pico_v2

    OP19: SMARTer_pico_v2

    BM16: SMARTer_pico_v2

    Ctrl: SMARTer_pico_v2

    LP: SMARTer_pico_v2

    BM20_alisa: SMARTer_pico_v2

    SRR13795948: SMARTer_pico_v2

    SRR13795968: SMARTer_pico_v2

    SRR13795969: SMARTer_pico_v2

    SRR13796010: SMARTer_pico_v2

    SRR13796112: SMARTer_pico_v2

    SRR13796113: SMARTer_pico_v2

    SRR13796114: SMARTer_pico_v2

    SRR13796120: SMARTer_pico_v2

    SRR13796121: SMARTer_pico_v2

    SRR13795952: SMARTer_pico_v2

    SRR13795964: SMARTer_pico_v2

    SRR13795965: SMARTer_pico_v2

    SRR13796011: SMARTer_pico_v2

    SRR13796110: SMARTer_pico_v2

    SRR13796111: SMARTer_pico_v2

    SRR13796115: SMARTer_pico_v2

    SRR13796118: SMARTer_pico_v2

    SRR13796119: SMARTer_pico_v2

