SAMPLES: [NCOV3265CHOA,NCOV3287CHOA,NCOV3289CHOA,NCOV3312CHOA,NCOV3318CHOA,NCOV3329CHOA,NCOV3333CHOA,NCOV3342CHOA,NCOV3343CHOA]

PROJECT: 
    'NCOV3265CHOA': MISC_DNA_test

    'NCOV3287CHOA': MISC_DNA_test

    'NCOV3289CHOA': MISC_DNA_test

    'NCOV3312CHOA': MISC_DNA_test

    'NCOV3318CHOA': MISC_DNA_test

    'NCOV3329CHOA': MISC_DNA_test

    'NCOV3333CHOA': MISC_DNA_test

    'NCOV3342CHOA': MISC_DNA_test

    'NCOV3343CHOA': MISC_DNA_test

PREP: 
    'NCOV3265CHOA': SMARTer_pico_v2

    'NCOV3287CHOA': SMARTer_pico_v2

    'NCOV3289CHOA': SMARTer_pico_v2

    'NCOV3312CHOA': SMARTer_pico_v2

    'NCOV3318CHOA': SMARTer_pico_v2

    'NCOV3329CHOA': SMARTer_pico_v2

    'NCOV3333CHOA': SMARTer_pico_v2

    'NCOV3342CHOA': SMARTer_pico_v2

    'NCOV3343CHOA': SMARTer_pico_v2

REF_DICT: 
    'NCOV3265CHOA': HG38

    'NCOV3287CHOA': HG38

    'NCOV3289CHOA': HG38

    'NCOV3312CHOA': HG38

    'NCOV3318CHOA': HG38

    'NCOV3329CHOA': HG38

    'NCOV3333CHOA': HG38

    'NCOV3342CHOA': HG38

    'NCOV3343CHOA': HG38

