# MODELS: GLM
MODELS: GLMNETLasso #[C5, EXTRATREES, GLM, GLMNETLasso, GLMNETRidge, KNN, LDA, NB, NNET, PAM, RF, RPART, SVMLIN, SVMRAD]

OUTPUT: output/

## Samples to use ase comparison group
CONDITIONS: [viral_infection, COVID19]

## RELEVANT COLUMNS
id_column: "cfrna_id"                                           
group_column: "diagnosis"       

## Number of top differentially abundant genes to use
NUM_MARKERS: 150

## Path to occurance rds file
OCCURANCE_RDS: ../..//3_Multiclass_1v1/output/occur.rds

## DATA PATHS
meta_train_path: ../../0_DATA/meta_data_train.7030.csv
meta_test_path: ../../0_DATA/meta_data_test.7030.csv
meta_val_path: ../../0_DATA/meta_data_test.7030.csv

counts_train_path: ../../0_DATA/counts_train.7030.csv
counts_test_path: ../../0_DATA/counts_test.7030.csv
counts_val_path: ../../0_DATA/counts_test.7030.csv

counts_vst_train_path: ../../0_DATA/counts_train_vst.7030.csv
counts_vst_test_path: ../../0_DATA/counts_test_vst.7030.csv
counts_vst_val_path: ../../0_DATA/counts_test_vst.7030.csv